steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/projections-441011/my-flask-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/projections-441011/my-flask-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'my-flask-app',
      '--image', 'gcr.io/projections-441011/my-flask-app',
      '--platform', 'managed',
      '--region', 'us-east5-c'
    ]
